# .releaserc.yaml

# semantic-release configuration file
# Documentation: https://semantic-release.gitbook.io/semantic-release/usage/configuration

# Enable dry run mode to preview the next release without publishing or pushing any changes.
dryRun: false

# Branches are not explicitly specified here.
# By default, semantic-release will release from:
#   - master
#   - main
#   - next
#   - next-major
#   - beta (prerelease)
#   - alpha (prerelease)
#   - maintenance branches matching N.N.x, N.x.x, or N.x
# See: https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches

# Git tag format for releases (default: v${version})
# See: https://semantic-release.gitbook.io/semantic-release/usage/configuration#tagformat
tagFormat: 'v${version}'

# Plugins to use in the release pipeline
# See: https://semantic-release.gitbook.io/semantic-release/usage/plugins
plugins:
  - '@semantic-release/commit-analyzer'         # https://github.com/semantic-release/commit-analyzer
  - '@semantic-release/release-notes-generator' # https://github.com/semantic-release/release-notes-generator
  - '@semantic-release/github'                  # https://github.com/semantic-release/github
