name: Release

on:
  push:
    branches:
      - master
      - '[0-9]+.x'         # distribution branches (e.g. 1.x, 2.x)
      - '[0-9]+.[0-9]+.x'  # distribution branches (e.g. 1.2.x, 2.3.x)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # - name: Set up app environment and run tests
      #   run: |
      #     # Add environment setup and test commands here
      #     echo "Run your tests here"

      - name: Install semantic-release and plugins
        run: |
          grep -Eo '@semantic-release/[^": ]+' .releaserc.yaml | sort -u | xargs -r npm install --no-save semantic-release

      - name: Setup octo-sts
        uses: octo-sts/action@v1.0.0
        id: octo-sts
        with:
          scope: jburns24/sample-go
          identity: semantic-release

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: npx semantic-release